### ISSUE TITLE
Linking errors with `undefined reference`s

### ISSUE THREAD

**Issue by exetwezz** [exetwezz/minerva#1]
Something has happened, and the kernel does not compile successfully. Not sure if this was previously, but I personally didn't face this problem before. Linking is terminated with these errors:

```
lib/libcore.rlib(core.0.o): In function `core::mem::swap::h7c7c21239f7829da':
core.cgu-0.rs:(.text._ZN4core3mem4swap17h7c7c21239f7829daE+0x50): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `_$LT$core..result..Result$LT$U$C$$u20$V$GT$$u20$as$u20$core..ops..Carrier$GT$::translate::h8f1f58238fac2d11':
core.cgu-0.rs:(.text._ZN77_$LT$core..result..Result$LT$U$C$$u20$V$GT$$u20$as$u20$core..ops..Carrier$GT$9translate17h8f1f58238fac2d11E+0x74): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::panicking::panic_fmt::h8ff170efcf5d25fb':
core.cgu-0.rs:(.text._ZN4core9panicking9panic_fmt17h8ff170efcf5d25fbE+0x4f): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `core::iter::iterator::Iterator::count::he266f743284c4511':
core.cgu-0.rs:(.text._ZN4core4iter8iterator8Iterator5count17he266f743284c4511E+0x64): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::iter::iterator::Iterator::nth::h915acc7b1a66c2c1':
core.cgu-0.rs:(.text._ZN4core4iter8iterator8Iterator3nth17h915acc7b1a66c2c1E+0xbf): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::iter::iterator::Iterator::zip::h0ea0c4f62d618c3b':
core.cgu-0.rs:(.text._ZN4core4iter8iterator8Iterator3zip17h0ea0c4f62d618c3bE+0x7d): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::iter::iterator::Iterator::zip::hf6d072d021e06508':
core.cgu-0.rs:(.text._ZN4core4iter8iterator8Iterator3zip17hf6d072d021e06508E+0x7d): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::iter::iterator::Iterator::fold::h723388ef1a5b7568':
core.cgu-0.rs:(.text._ZN4core4iter8iterator8Iterator4fold17h723388ef1a5b7568E+0x79): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o):core.cgu-0.rs:(.text._ZN4core4iter5range86_$LT$impl$u20$core..iter..iterator..Iterator$u20$for$u20$core..ops..Range$LT$A$GT$$GT$4next17hac393ba80d47fa3fE+0x94): more undefined references to `_Unwind_Resume' follow
lib/libcore.rlib(core.0.o): In function `_$LT$I$u20$as$u20$core..iter..traits..IntoIterator$GT$::into_iter::hbd2f9e8ab5123497':
core.cgu-0.rs:(.text._ZN54_$LT$I$u20$as$u20$core..iter..traits..IntoIterator$GT$9into_iter17hbd2f9e8ab5123497E+0x5a): undefined reference to `memcpy'
core.cgu-0.rs:(.text._ZN54_$LT$I$u20$as$u20$core..iter..traits..IntoIterator$GT$9into_iter17hbd2f9e8ab5123497E+0x7a): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `_$LT$I$u20$as$u20$core..iter..traits..IntoIterator$GT$::into_iter::hd92c210b053ebece':
core.cgu-0.rs:(.text._ZN54_$LT$I$u20$as$u20$core..iter..traits..IntoIterator$GT$9into_iter17hd92c210b053ebeceE+0x5a): undefined reference to `memcpy'
core.cgu-0.rs:(.text._ZN54_$LT$I$u20$as$u20$core..iter..traits..IntoIterator$GT$9into_iter17hd92c210b053ebeceE+0x7a): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$::next::h082eecffbdf5712c':
core.cgu-0.rs:(.text._ZN91_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$4next17h082eecffbdf5712cE+0x8b): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$::next::hf8161780c65f8741':
core.cgu-0.rs:(.text._ZN91_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$4next17hf8161780c65f8741E+0x8b): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `_$LT$core..option..Option$LT$T$GT$$GT$::unwrap::hb4650ddb8f4c505a':
core.cgu-0.rs:(.text._ZN38_$LT$core..option..Option$LT$T$GT$$GT$6unwrap17hb4650ddb8f4c505aE+0x61): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `_$LT$core..option..Option$LT$T$GT$$GT$::map::h38c68adf668ce388':
core.cgu-0.rs:(.text._ZN38_$LT$core..option..Option$LT$T$GT$$GT$3map17h38c68adf668ce388E+0x88): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `_$LT$core..option..Option$LT$T$GT$$GT$::map::hc3bd92ff0afacac6':
core.cgu-0.rs:(.text._ZN38_$LT$core..option..Option$LT$T$GT$$GT$3map17hc3bd92ff0afacac6E+0x8f): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o):core.cgu-0.rs:(.text._ZN38_$LT$core..option..Option$LT$T$GT$$GT$8and_then17h0148d3b4e91d3d87E+0x95): more undefined references to `_Unwind_Resume' follow
lib/libcore.rlib(core.0.o): In function `core::fmt::Write::write_fmt::h805deb32f7412bf9':
core.cgu-0.rs:(.text._ZN4core3fmt5Write9write_fmt17h805deb32f7412bf9E+0x6b): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `_$LT$core..fmt..Write..write_fmt..Adapter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..fmt..Write$GT$::write_fmt::h007e542ee4cfa8aa':
core.cgu-0.rs:(.text._ZN96_$LT$core..fmt..Write..write_fmt..Adapter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..fmt..Write$GT$9write_fmt17h007e542ee4cfa8aaE+0x54): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `_$LT$core..fmt..Arguments$LT$$u27$a$GT$$u20$as$u20$core..fmt..Display$GT$::fmt::h3de3fa5125c1a083':
core.cgu-0.rs:(.text._ZN73_$LT$core..fmt..Arguments$LT$$u27$a$GT$$u20$as$u20$core..fmt..Display$GT$3fmt17h3de3fa5125c1a083E+0x67): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `core::fmt::write::h01dd988616240a97':
core.cgu-0.rs:(.text._ZN4core3fmt5write17h01dd988616240a97E+0x67): undefined reference to `memcpy'
core.cgu-0.rs:(.text._ZN4core3fmt5write17h01dd988616240a97E+0x2c6): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o):core.cgu-0.rs:(.text._ZN4core3fmt5write17h01dd988616240a97E+0x510): more undefined references to `memcpy' follow
lib/libcore.rlib(core.0.o): In function `core::fmt::Formatter::with_padding::h69a6f6bb0fb0bbb3':
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12with_padding17h69a6f6bb0fb0bbb3E+0x99): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::fmt::Formatter::with_padding::h8eb0e9673c0186de':
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12with_padding17h8eb0e9673c0186deE+0xa1): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::fmt::Formatter::with_padding::hca73e1f6cd5677e1':
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12with_padding17hca73e1f6cd5677e1E+0xa1): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `core::fmt::Formatter::write_fmt::h2e75a779d8ac2cae':
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter9write_fmt17h2e75a779d8ac2caeE+0x54): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `_$LT$char$u20$as$u20$core..str..pattern..Pattern$LT$$u27$a$GT$$GT$::into_searcher::hd42d632e10f2e2c1':
core.cgu-0.rs:(.text._ZN66_$LT$char$u20$as$u20$core..str..pattern..Pattern$LT$$u27$a$GT$$GT$13into_searcher17hd42d632e10f2e2c1E+0x9a): undefined reference to `memcpy'
lib/libcore.rlib(core.0.o): In function `core::iter::iterator::Iterator::count::_$u7b$$u7b$closure$u7d$$u7d$::h62853dab32a3ce44':
core.cgu-0.rs:(.text._ZN4core4iter8iterator8Iterator5count28_$u7b$$u7b$closure$u7d$$u7d$17h62853dab32a3ce44E+0x4a): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$::next::_$u7b$$u7b$closure$u7d$$u7d$::h5b9a790bf969a264':
core.cgu-0.rs:(.text._ZN91_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$4next28_$u7b$$u7b$closure$u7d$$u7d$17h5b9a790bf969a264E+0x79): undefined reference to `_Unwind_Resume'
lib/libcore.rlib(core.0.o): In function `_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$::next::_$u7b$$u7b$closure$u7d$$u7d$::h6e7b451e6fe4bffe':
core.cgu-0.rs:(.text._ZN91_$LT$core..iter..Zip$LT$A$C$$u20$B$GT$$u20$as$u20$core..iter..ZipImpl$LT$A$C$$u20$B$GT$$GT$4next28_$u7b$$u7b$closure$u7d$$u7d$17h6e7b451e6fe4bffeE+0x79): undefined reference to `_Unwind_Resume'
```

This is caused by undefined libc functions, which Rust/LLVM relies on, though libcore is linked against the rlibc, which is created specifically to eliminate this problem.

Trying to solve the problem currently...

**Comment by exetwezz** [comment]
Reverting Rust compiler version has solved the issue. Trying to find the latest working version.

**Comment by exetwezz** [comment]
OK, maybe something wrong with `rustup` happened. `2016-09-22` is the latest version available, and the kernel links as usual with it, but the script did install a newer version (possibly [`2016-09-24`](https://static.rust-lang.org/dist/2016-09-24/index.html)), which produced incompatible object files.

**Comment by exetwezz** [comment]
Alright, changing the order of libraries passed to the linker truly solves this.

**Comment by exetwezz** [comment]
I'm totally confused with this...

**Comment by exetwezz** [comment]
Definitely works with `rustc 1.13.0-nightly (f1f40f850 2016-09-09)`.
